// src/lib/api/index.ts

// Client
export { api, tokenStorage, ApiError, SpuriApiError } from './client';
export type { FetchOptions } from './client';

// Serviços
export {
  authService,
  emailService,
  perfilService,
  consultasService,
  eventSourcingService,
  estudanteService,
  academiaService,
  adminService,
} from './services';

// Hooks
export { useApi, useApiQuery } from '@/hooks/useApi';

// Tipos principais
export type {
  UserType,
  AdminType,
  AcademiaType,
  NivelEscolar,
  AnoEscolar,
  AnoSuperior,
  StatusEscolar,
  StatusSuperior,
  StatusGeral,
  StatusInscricao,
  Periodo,
  CursoType,
  MateriaType,
  LoginRequest,
  AuthResponse,
  ApiResponse,
  Nota,
  Falta,
  AprovacaoAno,
  AvaliacaoFinal,
  NotasEstudanteResponse,
  FaltasEstudanteResponse,
  AprovacoesEstudanteResponse,
  Evento,
  EventosEstudanteResponse,
  VerificarIntegridadeResponse,
  Curso,
  Materia,
  ListarCursosResponse,
  ListarMateriasResponse,
  EstudanteDetalhado,
  AcademiaDetalhada,
  AdminDetalhado,
  MeuPerfilResponse,
  ConsultarEstudanteResponse,
  ConsultarAcademiaResponse,
  ConsultarAdminResponse,
  BuscarUsuarioResponse,
  ConsultarAcademiasResponse,
  ConsultarEstudantesResponse,
  ListarAdminsResponse,
  AtualizarStatusResponse,
  CriarEscolaRequest,
  CriarUniversidadeRequest,
  CriarEstudanteRequest,
  RegistrarNotasRequest,
  RegistrarFaltasRequest,
  RegistrarAprovacaoAnoRequest,
  RegistrarAvaliacaoFinalRequest,
  ListarAvaliacoesResponse,
  AvaliacoesEstudanteResponse,
  ListarAprovacoesResponse,
  ListarReprovacoesResponse,
  CriarAdminRequest,
  DesativarRequest,
  AtualizarStatusRequest,
  CriarCursoRequest,
  AtualizarCursoRequest,
  CriarMateriaRequest,
  AtualizarMateriaRequest,
  DefinirPeriodoMateriaRequest,
  AtualizarDadosPessoaisEstudanteRequest,
  AtualizarDadosAcademicosEstudanteRequest,
  AtualizarDadosAcademiaRequest,
  AtualizarDadosAdminRequest,
  AtualizarRoleAdminRequest,
  AlterarSenhaRequest,
  SolicitarRecuperacaoRequest,
  RegistroCompleto,
  RegistrosPorEstudanteResponse,
  Provincia,
  ProvinciaNome,
  ProvinciaCodigo,
  Provincias,
  DefinirAnoLetivoRequest,
  DefinirAnoLetivoResponse,
  AnoLetivoResponse,
  formatAnoLetivo,
  gerarOpcoesAnoLetivo,
  TipoNota,
  CategoriaNota,
  CategoriaNotaEscolar,
  CategoriaNotaSuperiorFixa,
  AtualizarNotaRequest,
  CriarCategoriaNotaRequest,
  CategoriaNotaItem,
  ListarCategoriasNotaResponse,
  Genero,
  Turma,
  ListarTurmasResponse,
  CriarTurmaRequest,
  AtualizarTurmaRequest,
  AdicionarEstudanteTurmaRequest,
  DeletarTurmaResponse,
  DeletarCursoResponse,
  StatusEscolarFundamental,
  StatusEscolarMedio,
  AtualizarFaltaRequest,
} from '@/types/api';