// src/lib/api/index.ts

// Client
export { api, tokenStorage, ApiError, SpuriApiError } from './client';
export type { FetchOptions } from './client';

// Serviços
export {
  academiaService,
  estudanteService,
  inscricoesService,
  consultasService,
  eventSourcingService,
  adminService,
  perfilService,
} from './services';

// Hooks
export { useApi, useApiQuery } from '@/hooks/useApi';

// Tipos principais
export type {
  UserType,
  AdminType,
  AcademiaType,
  NivelEscolar,
  AnoEscolar,
  AnoSuperior,
  StatusEscolar,
  StatusSuperior,
  StatusGeral,
  StatusInscricao,
  Periodo,
  CursoType,
  MateriaType,
  LoginRequest,
  AuthResponse,
  ApiResponse,
  Inscricao,
  ListarInscricoesResponse,
  InscricaoResponse,
  Nota,
  Falta,
  AprovacaoAno,
  NotasEstudanteResponse,
  FaltasEstudanteResponse,
  AprovacoesEstudanteResponse,
  HistoricoCompletoResponse,
  Evento,
  EventosEstudanteResponse,
  VerificarIntegridadeResponse,
  Curso,
  Materia,
  ListarCursosResponse,
  ListarMateriasResponse,
  EstudanteDetalhado,
  AcademiaDetalhada,
  AdminDetalhado,
  MeuPerfilResponse,
  ConsultarEstudanteResponse,
  ConsultarAcademiaResponse,
  ConsultarAdminResponse,
  BuscarUsuarioResponse,
  ConsultarAcademiasResponse,
  ConsultarEstudantesResponse,
  ListarAdminsResponse,
  PrimeiroAdminResponse,
  ListarInscricoesAprovadasResponse,
  GetInscricoesPorCodigoResponse,
  AlterarCursoResponse,
  VincularAcademiaResponse,
  AtualizarStatusResponse,
  CriarEscolaRequest,
  CriarUniversidadeRequest,
  CriarEstudanteRequest,
  SolicitarInscricaoEscolaRequest,
  SolicitarInscricaoUniversidadeRequest,
  RegistrarNotasRequest,
  RegistrarFaltasRequest,
  RegistrarAprovacaoAnoRequest,
  CriarAdminRequest,
  DesativarRequest,
  VincularAcademiaRequest,
  AtualizarStatusRequest,
  CriarCursoRequest,
  AtualizarCursoRequest,
  CriarMateriaRequest,
  AtualizarMateriaRequest,
  AtualizarDadosPessoaisEstudanteRequest,
  AtualizarDadosAcademicosEstudanteRequest,
  AtualizarDadosAcademiaRequest,
  AtualizarDadosAdminRequest,
  AtualizarRoleAdminRequest,
  AlterarSenhaRequest,
  SolicitarRecuperacaoRequest,
  SolicitarVerificacaoRequest,
  AlterarCursoRequest,
  RegistroCompleto,
  RegistrosPorEstudanteResponse,
  RegistrosPorAcademiaResponse,
  Provincia,
  ProvinciaNome,
  ProvinciaCodigo,
  Provincias,
  DefinirAnoLetivoRequest,
  DefinirAnoLetivoResponse,
  AnoLetivoResponse,
  formatAnoLetivo,
  gerarOpcoesAnoLetivo,
  TipoNota,
  CategoriaNota,
  CategoriaNotaEscolar,
  CategoriaNotaSuperiorFixa,
  AtualizarNotaRequest,
  CriarCategoriaNotaRequest,
  CategoriaNotaItem,
  ListarCategoriasNotaResponse,
} from '@/types/api';