// src/lib/api/index.ts

// Client
export { api, tokenStorage, ApiError, SpuriApiError } from './client';
export type { ApiErrorCode, ApiErrorDetail, ApiErrorEnvelope, FetchOptions } from './client';

// Serviços
export {
  authService,
  emailService,
  perfilService,
  consultasService,
  eventSourcingService,
  estudanteService,
  documentosService,
  academiaService,
  adminService,
  solicitacaoMatriculaService,
} from './services';

// Hooks
export { useApi, useApiQuery } from '@/hooks/useApi';

// Tipos principais
export type {
  UserType,
  AdminType,
  AdminRole,
  AcademiaType,
  NivelEscolar,
  AnoEscolar,
  AnoFundamental,
  AnoMedio,
  AnoSuperior,
  AnoAcademico,
  StatusEscolar,
  StatusSuperior,
  StatusGeral,
  StatusGeralEstudante,
  Periodo,
  CursoType,
  ModeloCursoMedio,
  MateriaType,
  Turno,
  LoginRequest,
  AuthResponse,
  ApiResponse,
  Nota,
  Falta,
  AprovacaoAno,
  AvaliacaoFinal,
  NotasEstudanteResponse,
  FaltasEstudanteResponse,
  AprovacoesEstudanteResponse,
  Evento,
  EventosEstudanteResponse,
  VerificarIntegridadeResponse,
  Curso,
  Materia,
  ListarCursosResponse,
  ListarMateriasResponse,
  EstudanteDetalhado,
  AcademiaDetalhada,
  AdminDetalhado,
  MeuPerfilResponse,
  ConsultarEstudanteResponse,
  ConsultarAcademiaResponse,
  BuscarUsuarioResponse,
  ConsultarAcademiasResponse,
  ConsultarEstudantesResponse,
  ListarAdminsResponse,
  CriarEscolaRequest,
  CriarUniversidadeRequest,
  CriarEstudanteRequest,
  MotivoEstudanteRequest,
  RevincularEstudanteRequest,
  MensagemResponse,
  RegistrarNotasRequest,
  RegistrarNotaResponse,
  AvaliacaoFinalFormulaTextual,
  CriarRegraAvaliacaoFinalRequest,
  CriarRegraAvaliacaoFinalResponse,
  RegraAvaliacaoFinal,
  ListarRegrasAvaliacaoFinalResponse,
  AvaliacaoFinalAutomaticaResultado,
  RegistrarFaltasRequest,
  RegistrarAprovacaoAnoRequest,
  RegistrarAvaliacaoFinalRequest,
  ListarAvaliacoesResponse,
  AvaliacoesEstudanteResponse,
  ListarAprovacoesResponse,
  ListarReprovacoesResponse,
  CriarAdminRequest,
  DesativarRequest,
  CriarCursoRequest,
  AtualizarCursoRequest,
  CriarMateriaRequest,
  AtualizarMateriaRequest,
  AtualizarDadosPessoaisEstudanteRequest,
  AtualizarDadosAcademicosEstudanteRequest,
  AtualizarDadosAcademiaRequest,
  AtualizarDadosAdminRequest,
  AtualizarRoleAdminRequest,
  AlterarSenhaRequest,
  SolicitarRecuperacaoRequest,
  Provincia,
  ProvinciaNome,
  ProvinciaCodigo,
  Provincias,
  DefinirAnoLetivoAcademiaRequest,
  DefinirAnoLetivoGlobalRequest,
  DefinirAnoLetivoRequest,
  DefinirAnoLetivoResponse,
  DefinirAnoLetivoGlobalResponse,
  AnoLetivoAcademiaResponse,
  AnoLetivoResponse,
  formatAnoLetivo,
  gerarOpcoesAnoLetivo,
  TipoNota,
  CategoriaNota,
  CategoriaNotaEscolar,
  CriarCategoriaNotaRequest,
  CategoriaNotaItem,
  ListarCategoriasNotaResponse,
  Genero,
  Turma,
  ListarTurmasResponse,
  TurmasEstudanteResponse,
  CriarTurmaRequest,
  AtualizarTurmaRequest,
  AdicionarEstudanteTurmaRequest,
  DeletarTurmaResponse,
  DeletarCursoResponse,
  StatusEscolarFundamental,
  StatusEscolarMedio,
  TipoEnsino,
  SolicitacaoMatriculaStatus,
  SolicitacaoStatusAcademicoTipo,
  SolicitacaoStatusAcademicoStatus,
  CriarSolicitacaoStatusAcademicoRequest,
  CriarSolicitacaoRevinculacaoRequest,
  CriarSolicitacaoStatusAcademicoResponse,
  SolicitacaoStatusAcademico,
  ListarSolicitacoesStatusAcademicoParams,
  ListarSolicitacoesStatusAcademicoResponse,
  DecidirSolicitacaoStatusAcademicoRequest,
  ReprovarSolicitacaoStatusAcademicoRequest,
  DecidirSolicitacaoStatusAcademicoResponse,
  DocumentosObrigatorios,
  AtualizarDocumentosObrigatoriosRequest,
  DocumentosObrigatoriosResponse,
  CriarSolicitacaoMatriculaRequest,
  CriarSolicitacaoMatriculaResponse,
  SolicitacaoMatricula,
  ListarSolicitacoesMatriculaParams,
  ListarSolicitacoesMatriculaResponse,
  StorageQuotaResponse,
} from '@/types/api';

// Jobs
export { jobApiService, pollJob, subscribeToJobStream } from './job-service';
export type {
  JobStatus,
  JobType,
  JobSummary,
  JobDetail,
  JobItemResult,
  JobEventType,
  JobStreamEvent,
  JobStreamOptions,
  AsyncBatchResponse,
  PollOptions,
} from './job-service';
export { useAsyncBatch } from '@/hooks/useAsyncBatch';
export type { AsyncBatchState, UseAsyncBatchOptions, UseAsyncBatchReturn } from '@/hooks/useAsyncBatch';
