"use client";
import { useEffect, useMemo, useState } from "react";
import { financeiroService, tokenStorage, useApi } from "@/lib/api";
import { formatApiError } from "@/lib/api/client";
import { useUserCookie } from "@/hooks/useUserCookie";
import Alert from "@/components/ui/alert/Alert";
import Button from "@/components/ui/button/Button";
import Input from "@/components/form/input/InputField";
import { Modal } from "@/components/ui/modal";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/components/ui/table";
import { CobrancasTable, badge, money, Qr } from "@/components/paineis/FinanceiroPagamentosPainel";
import type { FinanceiroMetodoPagamento, MensalidadeMesView } from "@/types/api";

const mesNome=(m:number)=>new Intl.DateTimeFormat("pt-AO",{month:"long"}).format(new Date(2026,m-1,1));
function getCodigo(user:any){return user?.estudante?.codigo_estudante || user?.estudante?.codigo || user?.codigo;}
export default function EstudantePagamentosPainel(){
 const {user,loading}=useUserCookie(); const restricted=tokenStorage.isRestrictedFinance(); const codigo=getCodigo(user); const mensalidades=useApi(financeiroService.consultarMensalidadesEstudante); const historico=useApi(financeiroService.consultarCobrancasEstudante); const pagar=useApi(financeiroService.iniciarPagamentoMensalidades); const [estado,setEstado]=useState(""); const [payAcademia,setPayAcademia]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [metodo,setMetodo]=useState<FinanceiroMetodoPagamento>("GPO"); const [telefone,setTelefone]=useState(""); const [alert,setAlert]=useState<string|null>(null); const [result,setResult]=useState<any>(null);
 const reload=async()=>{if(!codigo)return; await mensalidades.execute(codigo); if(!restricted) await historico.execute(codigo,{limit:100,offset:0});};
 useEffect(()=>{if(!loading&&codigo) void reload().catch(e=>setAlert(formatApiError(e,"Não foi possível carregar pagamentos.")))},[loading,codigo,restricted]);
 const filtered=(mensalidades.data?.mensalidades??[]).filter(m=>!estado||m.estado===estado); const byAcademia=useMemo(()=>filtered.reduce<Record<string,MensalidadeMesView[]>>((acc,m)=>{(acc[m.codigo_academia]??=[]).push(m);return acc},{}),[filtered]);
 const openPay=(academia:string, meses:MensalidadeMesView[])=>{const pend=meses.filter(m=>m.estado==="pendente").sort((a,b)=>a.ano_letivo.localeCompare(b.ano_letivo)||a.mes-b.mes); setPayAcademia(academia); setSelected(pend[0]?[`${pend[0].ano_letivo}:${pend[0].mes}`]:[]); setMetodo((mensalidades.data?.metodos_pagamento_por_academia[academia]?.[0]??"GPO") as FinanceiroMetodoPagamento); setTelefone(""); setResult(null);};
 const confirm=async()=>{try{const meses=selected.map(x=>{const [ano_letivo,mes]=x.split(":");return {ano_letivo,mes:Number(mes)}}); const r=await pagar.execute({codigo_academia:payAcademia,meses,metodo_pagamento:metodo,telefone:metodo==="GPO"?telefone:undefined}); setResult(r); await reload();}catch(e){setAlert(formatApiError(e,"Não foi possível iniciar o pagamento."))}};
 if(loading)return <div>Carregando...</div>; if(!codigo)return <Alert variant="error" title="Pagamentos" message="Não foi possível identificar o estudante logado."/>;
 return <div className="space-y-6">{restricted&&<Alert variant="warning" title="Acesso financeiro restrito" message="O seu vínculo com a academia foi encerrado. Você pode consultar e regularizar pendências financeiras aqui."/>}{alert&&<Alert variant="error" title="Pagamentos" message={alert}/>}<section className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><h1 className="text-xl font-semibold">Meus pagamentos</h1><div className="mt-4"><select className="rounded border p-2" value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos estados</option><option value="pendente">Pendentes</option><option value="pago">Pagos</option><option value="anulado">Anulados</option></select></div>{Object.entries(byAcademia).map(([academia,rows])=><div key={academia} className="mt-5 rounded-xl border p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Academia {academia}</h2>{rows.some(m=>m.estado==="pendente")&&<Button size="sm" onClick={()=>openPay(academia,rows)}>Pagar mensalidades</Button>}</div><div className="mt-3 overflow-x-auto"><Table><TableHeader><TableRow>{["Ano letivo","Mês","Valor","Estado"].map(h=><TableCell key={h} isHeader className="px-3 py-2 text-xs uppercase text-gray-500">{h}</TableCell>)}</TableRow></TableHeader><TableBody>{rows.map((m,i)=><TableRow key={i}><TableCell className="px-3 py-2">{m.ano_letivo}</TableCell><TableCell className="px-3 py-2">{mesNome(m.mes)}</TableCell><TableCell className="px-3 py-2">{money(m.valor)}</TableCell><TableCell className="px-3 py-2">{badge(m.estado)}</TableCell></TableRow>)}</TableBody></Table></div></div>)}</section><section className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><h2 className="font-semibold">Histórico completo de cobranças</h2>{restricted?<p className="mt-2 text-sm text-gray-500">Histórico completo indisponível nesta sessão restrita; apenas mensalidades e pagamento estão liberados.</p>:<CobrancasTable rows={historico.data?.cobrancas??[]} onOpen={()=>{}}/>}</section>
 <Modal isOpen={!!payAcademia} onClose={()=>setPayAcademia("")} className="max-w-xl p-6"><h3 className="text-lg font-semibold">Pagar mensalidades</h3>{result?<div className="mt-4 space-y-3"><p>Status: {result.cobranca.status}</p>{metodo==="GPO"&&<p>Você receberá uma notificação no telefone informado para confirmar o pagamento.</p>}{metodo==="REF"&&<pre className="rounded bg-gray-50 p-3 text-xs">{JSON.stringify(result.cobranca.response??{},null,2)}</pre>}{metodo==="GPO_QR"&&<Qr value={result.cobranca.qrCodeArr}/>}<Button size="sm" onClick={()=>void reload()}>Verificar status</Button></div>:<div className="mt-4 space-y-4">{(mensalidades.data?.mensalidades??[]).filter(m=>m.codigo_academia===payAcademia&&m.estado==="pendente").sort((a,b)=>a.ano_letivo.localeCompare(b.ano_letivo)||a.mes-b.mes).map((m,i)=>{const key=`${m.ano_letivo}:${m.mes}`;return <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(key)} disabled={i===0} onChange={e=>setSelected(s=>e.target.checked?[...s,key]:s.filter(x=>x!==key))}/>{m.ano_letivo} · {mesNome(m.mes)} · {money(m.valor)} {i===0&&"(mais antigo obrigatório)"}</label>})}<select className="w-full rounded border p-2" value={metodo} onChange={e=>setMetodo(e.target.value as FinanceiroMetodoPagamento)}>{(mensalidades.data?.metodos_pagamento_por_academia[payAcademia]??["GPO"]).map(m=><option key={m} value={m}>{m}</option>)}</select>{metodo==="GPO"&&<Input placeholder="Telefone" value={telefone} onChange={e=>setTelefone(e.target.value)}/>}<Button disabled={!selected.length || (metodo==="GPO"&&!telefone)} onClick={confirm}>Confirmar pagamento</Button></div>}</Modal></div>;
}
