"use client";
import { useEffect, useMemo, useState } from "react";
import { consultasService, financeiroService, useApi } from "@/lib/api";
import { formatApiError } from "@/lib/api/client";
import { useUserType } from "@/hooks/useRoutePermission";
import UnauthorizedAccess from "@/components/guards/UnauthorizedAccess";
import Alert from "@/components/ui/alert/Alert";
import Button from "@/components/ui/button/Button";
import SearchableSelect from "@/components/form/SearchableSelect";
import { Modal } from "@/components/ui/modal";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/components/ui/table";
import type { AcademiaDetalhada, ChargeResult, CobrancaResumo, FinanceiroOrigemCobranca } from "@/types/api";

const money=(v:number)=>new Intl.NumberFormat("pt-AO",{style:"currency",currency:"AOA"}).format(v);
const dt=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("pt-AO",{dateStyle:"short",timeStyle:"short"}).format(d)};
const badge=(s:string)=>{const x=s.toLowerCase(); const cls=x.includes("success")||x.includes("pago")?"bg-green-100 text-green-700":x.includes("pend")?"bg-amber-100 text-amber-700":x.includes("fail")||x.includes("falh")?"bg-red-100 text-red-700":x.includes("cancel")?"bg-gray-200 text-gray-700":"bg-blue-100 text-blue-700"; return <span className={`rounded-full px-2 py-1 text-xs font-medium ${cls}`}>{s}</span>};
const origemLabel: Record<FinanceiroOrigemCobranca,string>={matricula:"Matrícula",mensalidade:"Mensalidade",avulsa:"Avulsa"};
function Qr({ value }: { value?: string }) { if (!value) return null; return value.startsWith("data:image") ? <> {/* eslint-disable-next-line @next/next/no-img-element */}<img src={value} alt="QR Code" className="max-h-64 rounded border p-2"/></> : <pre className="whitespace-pre-wrap rounded bg-gray-50 p-3 text-xs dark:bg-gray-800">{value}</pre>; }
function CobrancasTable({ rows, onOpen }: { rows: CobrancaResumo[]; onOpen: (r:CobrancaResumo)=>void }) { return <div className="overflow-x-auto"><Table><TableHeader><TableRow>{["Origem","Descrição","Estudante","Valor","Método","Estado","Atualizado em"].map(h=><TableCell key={h} isHeader className="px-3 py-2 text-xs uppercase text-gray-500">{h}</TableCell>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id} className="cursor-pointer hover:bg-gray-50 dark:hover:bg-white/[0.03]" onClick={()=>onOpen(r)}><TableCell className="px-3 py-2">{origemLabel[r.origem]??r.origem}</TableCell><TableCell className="px-3 py-2">{r.descricao || "—"}</TableCell><TableCell className="px-3 py-2">{r.codigo_estudante || "—"}</TableCell><TableCell className="px-3 py-2">{money(r.valor)}</TableCell><TableCell className="px-3 py-2">{r.metodo_pagamento || "—"}</TableCell><TableCell className="px-3 py-2">{badge(r.status)}</TableCell><TableCell className="px-3 py-2">{dt(r.atualizado_em)}</TableCell></TableRow>)}</TableBody></Table></div> }
export { CobrancasTable, badge, money, Qr };

export default function FinanceiroPagamentosPainel(){
 const {user,isAdmin,isAcademia,loading}=useUserType(); const isFpp=isAdmin&&user?.admin?.role==="fpp"; const [academias,setAcademias]=useState<AcademiaDetalhada[]>([]); const [codigoAcademia,setCodigoAcademia]=useState(user?.academia?.codigo_academia??""); const [tipo,setTipo]=useState<""|FinanceiroOrigemCobranca>(""); const [estado,setEstado]=useState(""); const [page,setPage]=useState(0); const [alert,setAlert]=useState<string|null>(null); const [selected,setSelected]=useState<CobrancaResumo|null>(null); const [detail,setDetail]=useState<ChargeResult|null>(null); const [codigoEstudante,setCodigoEstudante]=useState(""); const [estudantes,setEstudantes]=useState<any[]>([]);
 const list=useApi(financeiroService.listarCobrancas); const detailApi=useApi(financeiroService.consultarCobranca); const cancelApi=useApi(financeiroService.cancelarCobranca); const mens=useApi(financeiroService.consultarMensalidadesEstudante); const hist=useApi(financeiroService.consultarCobrancasEstudante); const la=useApi(consultasService.listarAcademias); const le=useApi(consultasService.listarEstudantes);
 useEffect(()=>{
  // eslint-disable-next-line react-hooks/set-state-in-effect
  if(user?.academia?.codigo_academia)setCodigoAcademia(user.academia.codigo_academia)
 },[user?.academia?.codigo_academia]);
 useEffect(()=>{if(isFpp)la.execute({status:"ativo"}).then(r=>setAcademias(r?.academias??[])).catch(e=>setAlert(formatApiError(e,"Erro ao carregar academias.")))},[isFpp,la.execute]);
 useEffect(()=>{if(isAcademia||isFpp)le.execute({ codigo_academia: isAcademia?codigoAcademia:undefined }).then(r=>setEstudantes(r?.estudantes??[])).catch(()=>{})},[isAcademia,isFpp,codigoAcademia,le.execute]);
 const load=()=>{if(!codigoAcademia)return; return list.execute({contexto_tipo:"academia",codigo_academia:codigoAcademia,limit:20,offset:page*20,tipo:tipo?[tipo]:undefined,estado:estado?[estado]:undefined}).catch(e=>setAlert(formatApiError(e,"Não foi possível carregar cobranças.")))};
 useEffect(()=>{if(!loading&&(isAcademia||isFpp)&&codigoAcademia)void list.execute({contexto_tipo:"academia",codigo_academia:codigoAcademia,limit:20,offset:page*20,tipo:tipo?[tipo]:undefined,estado:estado?[estado]:undefined}).catch(e=>setAlert(formatApiError(e,"Não foi possível carregar cobranças.")))},[loading,isAcademia,isFpp,codigoAcademia,page,tipo,estado,list]);
 const open=async(r:CobrancaResumo)=>{setSelected(r);try{setDetail(await detailApi.execute(r.id,{contexto_tipo:"academia",codigo_academia:codigoAcademia})??null)}catch(e){setAlert(formatApiError(e,"Não foi possível consultar cobrança."))}};
 if(loading)return <div>Carregando...</div>; if(!isAcademia&&!isFpp)return <UnauthorizedAccess requiredTypes={["Admin FPP","Academia"]} message="O módulo financeiro é exclusivo de administradores com papel FPP. A API bloqueia até a leitura para admins adm/gerente."/>;
 const academiaOptions=academias.map(a=>({value:a.codigo_academia,label:`${a.nome} (${a.codigo_academia})`})); const estudanteOptions=estudantes.map((e:any)=>({value:e.codigo_estudante,label:`${e.nome??e.codigo_estudante} (${e.codigo_estudante})`})); const estados=Array.from(new Set((list.data?.cobrancas??[]).map(c=>c.status)));
 return <div className="space-y-6">{alert&&<Alert variant="error" title="Finanças" message={alert}/>}<section className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><h2 className="text-xl font-semibold">Pagamentos</h2><p className="text-sm text-gray-500">Listagem real de cobranças AppyPay em todos os estados.</p>{isFpp&&<div className="mt-4"><SearchableSelect value={codigoAcademia} options={academiaOptions} onChange={v=>{setCodigoAcademia(v);setPage(0)}} placeholder="Selecione uma academia" isClearable/></div>}<div className="mt-4 flex flex-wrap gap-3"><select className="rounded border p-2" value={tipo} onChange={e=>{setTipo(e.target.value as any);setPage(0)}}><option value="">Todas origens</option><option value="matricula">Matrícula</option><option value="mensalidade">Mensalidade</option><option value="avulsa">Avulsa</option></select><select className="rounded border p-2" value={estado} onChange={e=>{setEstado(e.target.value);setPage(0)}}><option value="">Todos estados</option>{estados.map(e=><option key={e} value={e}>{e}</option>)}</select></div><div className="mt-4"><CobrancasTable rows={list.data?.cobrancas??[]} onOpen={open}/></div><div className="mt-4 flex items-center gap-3"><Button size="sm" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</Button><span className="text-sm">Página {page+1} · {list.data?.total_geral??0} cobranças</span><Button size="sm" disabled={!list.data || (page+1)*20 >= list.data.total_geral} onClick={()=>setPage(p=>p+1)}>Próxima</Button></div></section>
 <section className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><h2 className="font-semibold">Consultar mensalidades e histórico por estudante</h2><div className="mt-3"><SearchableSelect value={codigoEstudante} options={estudanteOptions} onChange={async v=>{setCodigoEstudante(v); if(v){await mens.execute(v); await hist.execute(v,{limit:50,offset:0});}}} placeholder="Selecione um estudante" isClearable/></div>{mens.data&&<div className="mt-4 overflow-x-auto"><h3 className="mb-2 text-sm font-semibold">Mensalidades</h3><Table><TableBody>{mens.data.mensalidades.map((m,i)=><TableRow key={i}><TableCell className="px-3 py-2">{m.ano_letivo}</TableCell><TableCell className="px-3 py-2">Mês {m.mes}</TableCell><TableCell className="px-3 py-2">{m.codigo_academia}</TableCell><TableCell className="px-3 py-2">{money(m.valor)}</TableCell><TableCell className="px-3 py-2">{badge(m.estado)}</TableCell></TableRow>)}</TableBody></Table></div>}{hist.data&&<div className="mt-6"><h3 className="mb-2 text-sm font-semibold">Histórico completo de cobranças</h3><CobrancasTable rows={hist.data.cobrancas} onOpen={open}/></div>}</section>
 <Modal isOpen={!!selected} onClose={()=>{setSelected(null);setDetail(null)}} className="max-w-2xl p-6"><h3 className="text-lg font-semibold">Detalhe da cobrança</h3>{detailApi.loading?<p>Carregando...</p>:detail&&<div className="mt-4 space-y-3 text-sm"><p><b>ID:</b> {detail.id}</p><p><b>Provider:</b> {detail.provider_charge_id || "—"}</p><p><b>Transação:</b> {detail.merchant_transaction_id}</p><p><b>Status:</b> {detail.status}</p><Qr value={(detail as any).qrCodeArr}/><pre className="max-h-80 overflow-auto rounded bg-gray-50 p-3 text-xs dark:bg-gray-800">{JSON.stringify(detail.response??{},null,2)}</pre><Button size="sm" disabled={cancelApi.loading} onClick={async()=>{try{await cancelApi.execute(detail.id, window.prompt("Motivo do cancelamento (opcional)")||undefined); setSelected(null); await load();}catch(e){setAlert(formatApiError(e,"Não foi possível cancelar."))}}}>Cancelar cobrança</Button></div>}</Modal></div>;
}
