"use client";
import { useEffect, useState } from "react";
import { academiaService, useApi } from "@/lib/api";
import { formatApiError } from "@/lib/api/client";
import type { MetodoPagamentoServico, ServicoExtra, ServicoExtraPayload, TipoCobrancaServico } from "@/types/api";
import Button from "@/components/ui/button/Button";
import Alert from "@/components/ui/alert/Alert";
import Checkbox from "@/components/form/input/Checkbox";
import Input from "@/components/form/input/InputField";
import TextArea from "@/components/form/input/TextArea";
import { Modal } from "@/components/ui/modal";

const pagamentos: MetodoPagamentoServico[] = ["GPO", "REF", "GPO_QR"];
type Form = { nome: string; descricao: string; categoria: string; pago: boolean; preco: string; tipo: TipoCobrancaServico; metodos: MetodoPagamentoServico[]; taxa: boolean; valorTaxa: string; metodosTaxa: MetodoPagamentoServico[]; anos: string; documento: boolean; instrucoes: string };
const vazio: Form = { nome: "", descricao: "", categoria: "", pago: false, preco: "", tipo: "unico", metodos: [], taxa: false, valorTaxa: "", metodosTaxa: [], anos: "", documento: false, instrucoes: "" };
const paraForm = (s: ServicoExtra): Form => ({ nome:s.nome, descricao:s.descricao ?? "", categoria:s.categoria ?? "", pago:s.pago, preco:s.preco?.toString() ?? "", tipo:s.tipo_cobranca ?? "unico", metodos:s.metodos_pagamento, taxa:s.tem_taxa_inscricao, valorTaxa:s.valor_taxa_inscricao?.toString() ?? "", metodosTaxa:s.metodos_pagamento_taxa_inscricao, anos:s.anos_academicos_disponiveis.join(", "), documento:s.documento_obrigatorio, instrucoes:s.documento_instrucoes ?? "" });
const valor = (f: Form): ServicoExtraPayload => { const p: ServicoExtraPayload = { nome:f.nome.trim(), descricao:f.descricao || undefined, categoria:f.categoria || undefined, pago:f.pago, tem_taxa_inscricao:f.taxa, anos_academicos_disponiveis:f.anos.split(",").map(x=>x.trim()).filter(Boolean), documento_obrigatorio:f.documento, documento_instrucoes:f.documento ? f.instrucoes || undefined : undefined }; if (f.pago) Object.assign(p,{ preco:Number(f.preco), tipo_cobranca:f.tipo, metodos_pagamento:f.metodos }); if (f.taxa) Object.assign(p,{ valor_taxa_inscricao:Number(f.valorTaxa), metodos_pagamento_taxa_inscricao:f.metodosTaxa }); return p; };
const igual = (a: unknown,b: unknown) => JSON.stringify(a) === JSON.stringify(b);
function Pagamentos({ value, onChange, label }: {value: MetodoPagamentoServico[]; onChange:(x:MetodoPagamentoServico[])=>void; label:string}) { return <div><p className="mb-2 text-sm font-medium text-gray-700 dark:text-gray-300">{label}</p><div className="flex gap-4">{pagamentos.map(m=><Checkbox key={m} label={m} checked={value.includes(m)} onChange={ok=>onChange(ok?[...value,m]:value.filter(x=>x!==m))}/>)}</div></div>; }
export default function ServicosExtrasPainel() {
 const lista=useApi(academiaService.listarServicosExtras), criar=useApi(academiaService.criarServicoExtra), atualizar=useApi(academiaService.atualizarServicoExtra), desativar=useApi(academiaService.desativarServicoExtra), reativar=useApi(academiaService.reativarServicoExtra);
 const [modal,setModal]=useState(false), [edicao,setEdicao]=useState<ServicoExtra|null>(null), [form,setForm]=useState<Form>(vazio), [alert,setAlert]=useState<{variant:"success"|"error"|"warning";message:string}|null>(null);
 useEffect(()=>{lista.execute();},[]); const set=(x:Partial<Form>)=>setForm(p=>({...p,...x}));
 const salvar=async(e:React.FormEvent)=>{e.preventDefault(); if(!form.nome.trim()) return setAlert({variant:"error",message:"O nome é obrigatório."}); if(form.pago && (!form.preco || !form.metodos.length)) return setAlert({variant:"error",message:"Informe preço e métodos de pagamento."}); if(form.taxa && (!form.valorTaxa || !form.metodosTaxa.length)) return setAlert({variant:"error",message:"Informe valor e métodos da taxa."}); try { const atual=valor(form); if(edicao) { const original=valor(paraForm(edicao)); const parcial=Object.fromEntries(Object.entries(atual).filter(([k,v])=>!igual(v,original[k as keyof ServicoExtraPayload]))) as ServicoExtraPayload; await atualizar.execute(edicao.id,parcial); } else await criar.execute(atual); setAlert({variant:"success",message:"Serviço salvo com sucesso."}); setModal(false); lista.execute(); } catch(e) { const m=formatApiError(e,"Não foi possível salvar o serviço."); setAlert({variant:"error",message:m}); }};
 const abrir=(s?:ServicoExtra)=>{setEdicao(s??null);setForm(s?paraForm(s):vazio);setModal(true)};
 const toggle=async(s:ServicoExtra)=>{if(!window.confirm(`Deseja ${s.ativo?"desativar":"reativar"} este serviço?`))return;try {await (s.ativo?desativar:reativar).execute(s.id);lista.execute()}catch(e){setAlert({variant:"error",message:formatApiError(e,"Não foi possível alterar o status.")})}};
 const credencial=alert?.message.toLowerCase().includes("credenciais") || alert?.message.toLowerCase().includes("appypay");
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Serviços Extras</h1><p className="text-sm text-gray-500">Gerencie os serviços adicionais da academia.</p></div><Button onClick={()=>abrir()}>Novo Serviço</Button></div>{alert && <Alert variant={alert.variant} title="Serviços extras" message={<>{alert.message} {credencial && <a className="underline font-medium" href="/financas/credenciais">Configurar credenciais</a>}</> as any}/>}<div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-800"><tr>{["Nome","Categoria","Pago","Taxa de Inscrição","Anos Acadêmicos","Status","Ações"].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{lista.data?.servicos_extras.map(s=><tr className="border-t border-gray-200 dark:border-gray-700" key={s.id}><td className="p-3 font-medium">{s.nome}</td><td className="p-3">{s.categoria||"-"}</td><td className="p-3">{s.pago?`Sim (${s.preco})`:"Não"}</td><td className="p-3">{s.tem_taxa_inscricao?`Sim (${s.valor_taxa_inscricao})`:"Não"}</td><td className="p-3">{s.anos_academicos_disponiveis.length?s.anos_academicos_disponiveis.join(", "):"Todos"}</td><td className="p-3"><span className={s.ativo?"text-green-600":"text-gray-500"}>{s.ativo?"Ativo":"Inativo"}</span></td><td className="p-3 whitespace-nowrap"><button className="mr-3 text-brand-600" onClick={()=>abrir(s)}>Editar</button><button className="text-brand-600" onClick={()=>toggle(s)}>{s.ativo?"Desativar":"Reativar"}</button></td></tr>)}{!lista.loading && !lista.data?.servicos_extras.length && <tr><td className="p-6 text-center text-gray-500" colSpan={7}>Nenhum serviço cadastrado.</td></tr>}</tbody></table></div>
 <Modal isOpen={modal} onClose={()=>setModal(false)} className="max-w-2xl p-6"><form className="space-y-4" onSubmit={salvar}><h2 className="text-xl font-semibold">{edicao?"Editar serviço":"Novo serviço"}</h2><div className="grid gap-4 sm:grid-cols-2"><Input value={form.nome} onChange={e=>set({nome:e.target.value})} placeholder="Nome"/><Input value={form.categoria} onChange={e=>set({categoria:e.target.value})} placeholder="Categoria"/></div><TextArea value={form.descricao} onChange={descricao=>set({descricao})} placeholder="Descrição"/><Checkbox label="Serviço pago" checked={form.pago} onChange={pago=>set({pago})}/>{form.pago&&<div className="space-y-3 rounded-lg bg-gray-50 p-3 dark:bg-gray-800"><Input type="number" value={form.preco} onChange={e=>set({preco:e.target.value})} placeholder="Preço"/><select className="h-11 w-full rounded-lg border p-2 dark:bg-gray-900" value={form.tipo} onChange={e=>set({tipo:e.target.value as TipoCobrancaServico})}><option value="unico">Único</option><option value="mensal">Mensal</option></select><Pagamentos label="Métodos de pagamento" value={form.metodos} onChange={metodos=>set({metodos})}/></div>}<Checkbox label="Tem taxa de inscrição" checked={form.taxa} onChange={taxa=>set({taxa})}/>{form.taxa&&<div className="space-y-3 rounded-lg bg-gray-50 p-3 dark:bg-gray-800"><Input type="number" value={form.valorTaxa} onChange={e=>set({valorTaxa:e.target.value})} placeholder="Valor da taxa"/><Pagamentos label="Métodos da taxa" value={form.metodosTaxa} onChange={metodosTaxa=>set({metodosTaxa})}/></div>}<Input value={form.anos} onChange={e=>set({anos:e.target.value})} placeholder="Anos acadêmicos, separados por vírgula" hint="Deixe vazio para disponibilizar para todos os anos."/><Checkbox label="Exige documento anexado na inscrição" checked={form.documento} onChange={documento=>set({documento})}/>{form.documento&&<TextArea value={form.instrucoes} onChange={instrucoes=>set({instrucoes})} placeholder="Instruções do documento"/>}<div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>setModal(false)}>Cancelar</Button><Button disabled={criar.loading||atualizar.loading}>{edicao?"Salvar":"Criar"}</Button></div></form></Modal></div>;
}
